# Generated by Django 4.1.7 on 2023-02-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bohdanwebsite', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link Above To Read Blog Post', max_length=255),
        ),
    ]
