# Generated by Django 4.1.7 on 2023-02-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bohdanwebsite', '0008_post_header_image_alter_post_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
    ]
